# Site settings
title: Stephanie Yan
baseurl: ""
url: "https://stephaniemyan.github.io/"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Stephanie Yan
  desc:
  email: syan[at]jhu[dot]edu
  selfie: assets/img/fb_profile_2.jpg

# social
social:
  email: true
  twitter: smyan__
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: stephaniemyan
  google_plus:
  instagram:
  keybase:
  linkedin: stephanie-yan-560805a4
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  vimeo:
  wordpress:
  youtube:
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "README.md"
